<?php

/**
 * @file
 * Theme hooks for Factory.
 */

// Include all files from the includes directory.
$includes_path = dirname(__FILE__) . '/includes/*.inc';
foreach (glob($includes_path) as $filename) {
  require_once dirname(__FILE__) . '/includes/' . basename($filename);
}

/**
 * Implements hook_preprocess().
 */
function portfolio_preprocess(&$variables, $hook) {
  $variables['base_path'] = base_path();
  $variables['route_name'] = \Drupal::routeMatch()->getRouteName();
}
